# Generated by Django 4.2.15 on 2024-08-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('mrp', models.CharField(max_length=25)),
                ('last_7_day_sale', models.CharField(max_length=25)),
                ('available_skus', models.TextField()),
                ('description', models.TextField()),
                ('specifications', models.TextField()),
            ],
        ),
    ]
